import 'package:equatable/equatable.dart';

/// A single reel (short video) in the feed.
///
/// Simplified to match the base-project backend (utd/reels). Rich user fields
/// (vip, levels, frames, gifts) are intentionally omitted — see NOTES_GAPS.md.
class RealEntity extends Equatable {
  final int id;
  final int userId;
  final String description;

  /// Playable video path/URL (`url` from the backend).
  final String url;

  /// Optional animated preview (`sub_video`) — may be empty (dropped in Base).
  final String subVideo;

  /// Poster frame path (`sub_frame`) generated by FFMpeg on the backend.
  final String subFrame;

  final int likesCount;
  final int commentsCount;
  final int viewsCount;
  final bool isLike;
  final int shareCount;
  final String createdAt;

  /// The current user's reaction type (like/love/haha/wow/sad/angry), or null.
  final String? myReaction;

  /// Per-type reaction counts, e.g. {like: 5, love: 2}.
  final Map<String, int> reactionsBreakdown;

  /// True when the current user authored this reel (backend `is_owner`).
  final bool isOwner;

  // author (flattened from the nested `user` object)
  final String userName;
  final String userImage;
  final String uuid;
  final int gender;
  final int? age;

  const RealEntity({
    required this.id,
    required this.userId,
    required this.description,
    required this.url,
    required this.subVideo,
    required this.subFrame,
    required this.likesCount,
    required this.commentsCount,
    this.viewsCount = 0,
    required this.isLike,
    required this.shareCount,
    required this.createdAt,
    this.myReaction,
    this.reactionsBreakdown = const {},
    this.isOwner = false,
    required this.userName,
    required this.userImage,
    required this.uuid,
    required this.gender,
    required this.age,
  });

  RealEntity copyWith({
    int? likesCount,
    int? commentsCount,
    bool? isLike,
    String? description,
    String? myReaction,
    bool clearMyReaction = false,
    Map<String, int>? reactionsBreakdown,
  }) {
    return RealEntity(
      id: id,
      userId: userId,
      description: description ?? this.description,
      url: url,
      subVideo: subVideo,
      subFrame: subFrame,
      likesCount: likesCount ?? this.likesCount,
      commentsCount: commentsCount ?? this.commentsCount,
      viewsCount: viewsCount,
      isLike: isLike ?? this.isLike,
      shareCount: shareCount,
      createdAt: createdAt,
      myReaction: clearMyReaction ? null : (myReaction ?? this.myReaction),
      reactionsBreakdown: reactionsBreakdown ?? this.reactionsBreakdown,
      isOwner: isOwner,
      userName: userName,
      userImage: userImage,
      uuid: uuid,
      gender: gender,
      age: age,
    );
  }

  @override
  List<Object?> get props => [id, likesCount, commentsCount, isLike, description, myReaction, reactionsBreakdown];
}
