<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('reals', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained('users')->onDelete('cascade');
            // Eagle widened this to 500 + nullable in a follow-up migration
            // (2023_10_15_edit_description_field_in_reals_table); folded in here.
            $table->string('description', 500)->nullable()->default('');
            $table->string('url');
            // sub_video (animated GIF preview) was generated by a Python script in
            // Eagle; dropped here (see NOTES_GAPS) — kept nullable so the API shape
            // (and the column) stays consistent. The poster frame is `sub_frame`,
            // computed from the id in RealsResource (FfmpegService writes it to gcs).
            $table->string('sub_video')->nullable();
            $table->integer('share_num')->default(0);
            $table->integer('comment_num')->default(0);
            $table->integer('like_num')->default(0);
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('reals');
    }
};
