const Map<String, Map<String, String>> profileTranslations = {
  'en': {
    'profile.menu_profile': 'Profile',
    'profile.title': 'Profile',
    'profile.error': 'Failed to load profile',
    'profile.retry': 'Retry',
    'profile.not_found': 'User not found',
    'profile.id': 'ID',
    'profile.copied': 'ID copied',
    'profile.coming_soon': 'Coming soon',
    'profile.preview_as_visitor': 'Visitor view',
    // Stats
    'profile.friend': 'Friend',
    'profile.following': 'Following',
    'profile.followers': 'Followers',
    'profile.visitors': 'Visitors',
    // SVIP banner
    'profile.svip_title': 'SVIP Club',
    'profile.svip_subtitle': 'Enjoy distinguished privileges',
    'profile.get_svip': 'Get SVIP',
    // Wallet
    'profile.diamonds': 'Diamonds',
    'profile.coins': 'Coins',
    // Feature grid
    'profile.level': 'Level',
    'profile.store': 'Store',
    'profile.tasks': 'Tasks',
    'profile.family': 'Family',
    'profile.vip': 'VIP',
    'profile.cp': 'CP',
    'profile.bd_center': 'BD Center',
    'profile.agency_center': 'Agency Center',
    'profile.my_post': 'My Post',
    'profile.offline_recharge': 'Offline Recharge',
    'profile.host_center': 'Host Center',
    'profile.my_videos': 'My Videos',
    'profile.settings': 'Settings',
    'profile.add_bio': 'Add a bio',
    // Cover banner
    'profile.cover': 'Cover',
    'profile.add_cover': 'Add a cover',
    'profile.manage_covers': 'Cover photos',
    'profile.max_covers_reached': 'You can add up to 3 covers',
    // Visited-profile content tabs
    'profile.tab_general': 'General',
  },
  'ar': {
    'profile.menu_profile': 'الملف الشخصي',
    'profile.title': 'الملف الشخصي',
    'profile.error': 'فشل تحميل الملف الشخصي',
    'profile.retry': 'إعادة المحاولة',
    'profile.not_found': 'المستخدم غير موجود',
    'profile.id': 'الأيدي',
    'profile.copied': 'تم نسخ الأيدي',
    'profile.coming_soon': 'قريبًا',
    'profile.preview_as_visitor': 'كما يراه الزائر',
    // Stats
    'profile.friend': 'الأصدقاء',
    'profile.following': 'يتابع',
    'profile.followers': 'المتابعون',
    'profile.visitors': 'الزوار',
    // SVIP banner
    'profile.svip_title': 'نادي SVIP',
    'profile.svip_subtitle': 'استمتع بامتيازات مميزة',
    'profile.get_svip': 'احصل على SVIP',
    // Wallet
    'profile.diamonds': 'الماس',
    'profile.coins': 'العملات',
    // Feature grid
    'profile.level': 'المستوى',
    'profile.store': 'المتجر',
    'profile.tasks': 'المهام',
    'profile.family': 'العائلة',
    'profile.vip': 'VIP',
    'profile.cp': 'CP',
    'profile.bd_center': 'مركز BD',
    'profile.agency_center': 'مركز الوكالة',
    'profile.my_post': 'منشوراتي',
    'profile.offline_recharge': 'شحن أوفلاين',
    'profile.host_center': 'مركز المضيف',
    'profile.my_videos': 'فيديوهاتي',
    'profile.settings': 'الإعدادات',
    'profile.add_bio': 'أضف نبذة',
    // Cover banner
    'profile.cover': 'الغلاف',
    'profile.add_cover': 'أضف صورة غلاف',
    'profile.manage_covers': 'صور الغلاف',
    'profile.max_covers_reached': 'يمكنك إضافة 3 صور غلاف كحد أقصى',
    // Visited-profile content tabs
    'profile.tab_general': 'عام',
  },
};
